visitor/urls.py
from django.urls import path , include

from visitor import views


app_name = "vizitor"
urlpatterns = [
    path('', views.index, name='index'),
    path('atividade', views.atividade, name='atividade'),
    path('konaba', views.konaba, name='konaba'),
    path('misa', views.misa, name='misa'),
    path('eventu', views.eventu, name='eventu'),
    path('anunsiu', views.anunsiu, name='anunsiu'),
    path('atendimentu', views.atendimentu, name='atendimentu'),
    path('planu', views.planu, name='planu'),
    path('detallu', views.detallu, name='detallu'),


                     
]


    

websajobril/urls.py
from django.contrib import admin
from django.urls import path



from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



from django.contrib import admin
from django.urls import path, include


from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('visitor.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visitor/models.py
from django.db import models

# Create your models here.

visitor/views.py
from django.shortcuts import render

# Create your views here.

visitor/views/view_visitor.py
import os
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt
import json
from django.utils import timezone

from django.db.models import Count
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import Q
from datetime import date
from django.http import JsonResponse

from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, logout


from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.http import HttpResponse
from django.utils import translation
from django.utils.translation import *
from django.contrib.auth.models import User

from django.http import HttpResponseRedirect


from django.template.loader import render_to_string

from django.contrib.auth.models import Group




def index(request):
    context = {
        'pajinauma' : 'active',
    }
    return render(request,'visitor/uma.html', context)



def atividade(request):
    context = {
        'pajinaatividade' : 'active',
    }
    return render(request,'visitor/atividade.html', context)

def konaba(request):
    context = {
        'pajinakonaba' : 'active',
    }
    return render(request,'visitor/konaba.html', context)


def misa(request):
    context = {
        'pajinamisa' : 'active',
    }
    return render(request,'visitor/misa.html', context)


def eventu(request):
    context = {
        'pajinaeventu' : 'active',
    }
    return render(request,'visitor/eventu.html', context)


def anunsiu(request):
    context = {
        'pajinaanunsiu' : 'active',
    }
    return render(request,'visitor/anunsiu.html', context)


def atendimentu(request):
    context = {
        'pajinaatendimentu' : 'active',
    }
    return render(request,'visitor/atendimentu.html', context)


def planu(request):
    context = {
        'pajinaplanu' : 'active',
    }
    return render(request,'visitor/planu.html', context)


def detallu(request):
    context = {
        'pajinadetallu' : 'active',
    }
    return render(request,'visitor/detallu.html', context)

visitor/templates/visitor/anunsiu.html
{% extends 'visitor/baze.html' %}
{% block content %}



  <section class="ftco-section">
          <div class="container">
              <div class="row justify-content-center mb-5 pb-2">
        <div class="col-md-8 text-center heading-section ftco-animate">
       
          <h2 class="mb-4">ANUNSIU</h2><hr><br>
          
      </div>
              <div class="row">
        <div class="col-md-4 ftco-animate">
          <div class="blog-entry">
            <a href="blog-single.html" class="block-20" style="background-image: url('images/image_1.jpg');">
                              <div class="meta-date text-center p-2">
                <span class="day">23</span>
                <span class="mos">January</span>
                <span class="yr">2019</span>
              </div>
            </a>
            <div class="text bg-white p-4">
              <h3 class="heading"><a href="#">Scary Thing That You Don’t Get Enough Sleep</a></h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="#" class="btn btn-sm btn-primary">Detallu <span class="ion-ios-arrow-round-forward"></span></a></p>
                  <!-- <p class="ml-auto mb-0">
                      <a href="#" class="mr-2">Admin</a>
                      <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                  </p> -->
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 ftco-animate">
          <div class="blog-entry">
            <a href="blog-single.html" class="block-20" style="background-image: url('images/image_2.jpg');">
                              <div class="meta-date text-center p-2">
                <span class="day">23</span>
                <span class="mos">January</span>
                <span class="yr">2019</span>
              </div>
            </a>
            <div class="text bg-white p-4">
              <h3 class="heading"><a href="#">Scary Thing That You Don’t Get Enough Sleep</a></h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="#" class="btn  btn-sm btn-primary">Detallu <span class="ion-ios-arrow-round-forward"></span></a></p>
                  <!-- <p class="ml-auto mb-0">
                      <a href="#" class="mr-2">Admin</a>
                      <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                  </p> -->
              </div>
            </div>



          </div>
          <hr>
          <center><a href="#" class="btn btn-primary">Hare atividade seluk <span class="ion-ios-arrow-round-forward"></span></a></center>
        </div>
        <div class="col-md-4 ftco-animate">
          <div class="blog-entry">
            <a href="blog-single.html" class="block-20" style="background-image: url('images/image_3.jpg');">
                              <div class="meta-date text-center p-2">
                <span class="day">23</span>
                <span class="mos">January</span>
                <span class="yr">2019</span>
              </div>
            </a>
            <div class="text bg-white p-4">
              <h3 class="heading"><a href="#">Scary Thing That You Don’t Get Enough Sleep</a></h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="#" class="btn btn-sm btn-primary">Detallu <span class="ion-ios-arrow-round-forward"></span></a></p>
                  <!-- <p class="ml-auto mb-0">
                      <a href="#" class="mr-2">Admin</a>
                      <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                  </p> -->
              </div>
            </div>
          </div>
        </div>
      </div>
          </div>
  </section>









{% endblock %}

visitor/templates/visitor/atendimentu.html
{% extends 'visitor/baze.html' %}
{% block content %}



  <section class="ftco-section">
          <div class="container">
              <div class="row justify-content-center mb-5 pb-2">
        <div class="col-md-8 text-center heading-section ftco-animate">
       
          <h2 class="mb-4">Atendimentu</h2><hr><br>
          
      </div>
              <div class="row">
        <div class="col-md-4 ftco-animate">
          <div class="blog-entry">
            <a href="blog-single.html" class="block-20" style="background-image: url('../media/sistem/doc.png');">
                              <div class="meta-date text-center p-2">
              
                <span class="mos">Kriteria obito</span>
               
              </div>
            </a>
            <div class="text bg-white p-4">
              <h3 class="heading"><a href="#">Formatu no criteria rejistu obito</a></h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="#" class="btn btn-sm btn-primary">Haree & Download Dokumentu  <span class="ion-ios-arrow-round-forward"></span></a></p>
                  <p class="ml-auto mb-0">
                      <a href="#" class="mr-2">Admin</a>
                      <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                  </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 ftco-animate">
          <div class="blog-entry">
            <a href="blog-single.html" class="block-20" style="background-image: url('../media/sistem/doc.png');">
                              <div class="meta-date text-center p-2">
              
                <span class="mos">Kriteria Kazamentu</span>
             
              </div>
            </a>
            <div class="text bg-white p-4">
              <h3 class="heading"><a href="#">Formatu rejistu casamentu</a></h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="#" class="btn  btn-sm btn-primary">Haree & Download Dokumentu <span class="ion-ios-arrow-round-forward"></span></a></p>
                  <p class="ml-auto mb-0">
                      <a href="#" class="mr-2">Admin</a>
                      <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                  </p>
              </div>
            </div>



          </div>
          <hr>
          <center><a href="#" class="btn btn-primary">Hare dokumentu seluk <span class="ion-ios-arrow-round-forward"></span></a></center>
        </div>
        <div class="col-md-4 ftco-animate">
          <div class="blog-entry">
            <a href="blog-single.html" class="block-20" style="background-image: url('../media/sistem/doc.png');">
                              <div class="meta-date text-center p-2">
               
                <span class="mos">Rejisistu sertidaun batismu</span>
              
              </div>
            </a>
            <div class="text bg-white p-4">
              <h3 class="heading"><a href="#">Formatu dokumentu no kriteria rejistu sertidaun baatismu</a></h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="#" class="btn btn-sm btn-primary">Haree & Download Dokumentu  <span class="ion-ios-arrow-round-forward"></span></a></p>
                  <p class="ml-auto mb-0">
                      <a href="#" class="mr-2">Admin</a>
                      <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                  </p>
              </div>
            </div>
          </div>
        </div>
      </div>
          </div>
  </section>









{% endblock %}

visitor/templates/visitor/atividade.html
{% extends 'visitor/baze.html' %}
{% block content %}



  <section class="ftco-section">
          <div class="container">
              <div class="row justify-content-center mb-5 pb-2">
        <div class="col-md-8 text-center heading-section ftco-animate">
       
          <h2 class="mb-4">Atividade Ikus liu</h2><hr><br>
          
      </div>
              <div class="row">
                <div class="col-md-4 ftco-animate">
                  <div class="blog-entry">
                    <a href="blog-single.html" class="block-20" style="background-image: url('../media/sistem/atividade1.jpeg');">
                                      <div class="meta-date text-center p-2">
                        <span class="day">23</span>
                        <span class="mos">January</span>
                        <span class="yr">2019</span>
                      </div>
                    </a>
                    <div class="text bg-white p-4">
                      <h3 class="heading"><a href="#">Scary Thing That You Don’t Get Enough Sleep</a></h3>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                      <div class="d-flex align-items-center mt-4">
                          <p class="mb-0"><a href="#" class="btn btn-sm btn-primary">Read More <span class="ion-ios-arrow-round-forward"></span></a></p>
                          <p class="ml-auto mb-0">
                              <a href="#" class="mr-2">Admin</a>
                              <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                          </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 ftco-animate">
                  <div class="blog-entry">
                    <a href="blog-single.html" class="block-20" style="background-image: url('../media/sistem/atividade2.jpeg');">
                                      <div class="meta-date text-center p-2">
                        <span class="day">23</span>
                        <span class="mos">January</span>
                        <span class="yr">2019</span>
                      </div>
                    </a>
                    <div class="text bg-white p-4">
                      <h3 class="heading"><a href="#">Scary Thing That You Don’t Get Enough Sleep</a></h3>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                      <div class="d-flex align-items-center mt-4">
                          <p class="mb-0"><a href="#" class="btn  btn-sm btn-primary">Read More <span class="ion-ios-arrow-round-forward"></span></a></p>
                          <p class="ml-auto mb-0">
                              <a href="#" class="mr-2">Admin</a>
                              <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                          </p>
                      </div>
                    </div>



                  </div>
                  <hr>
                  <center><a href="#" class="btn btn-primary">Hare atividade seluk <span class="ion-ios-arrow-round-forward"></span></a></center>
                </div>
                <div class="col-md-4 ftco-animate">
                  <div class="blog-entry">
                    <a href="blog-single.html" class="block-20" style="background-image: url('../media/sistem/atividade3.jpeg');">
                                      <div class="meta-date text-center p-2">
                        <span class="day">23</span>
                        <span class="mos">January</span>
                        <span class="yr">2019</span>
                      </div>
                    </a>
                    <div class="text bg-white p-4">
                      <h3 class="heading"><a href="#">Scary Thing That You Don’t Get Enough Sleep</a></h3>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                      <div class="d-flex align-items-center mt-4">
                          <p class="mb-0"><a href="#" class="btn btn-sm btn-primary">Read More <span class="ion-ios-arrow-round-forward"></span></a></p>
                          <p class="ml-auto mb-0">
                              <a href="#" class="mr-2">Admin</a>
                              <a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a>
                          </p>
                      </div>
                    </div>
                  </div>
                </div>
      </div>
          </div>
  </section>









{% endblock %}

visitor/templates/visitor/baze.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SAJOBRIL</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <nav class="navbar py-4 navbar-expand-lg ftco_navbar navbar-light bg-light flex-row">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-3 px-md-0">
    			<div class="col-lg-2 pr-4 align-items-center">
		    		<a class="navbar-brand" href="index.html"><font color='white'>Sajobril<span></span></font></a>
	    		</div>
	    		<div class="col-lg-10 d-none d-md-block">
		    		<div class="row d-flex">
			    		<div class="col-md-4 pr-4 d-flex topper align-items-center">
			    			<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-map"></span></div>
						    <span class="text"><font color='white'>Address: 198 West 21th Street, Suite 721 New York NY 10016</font></span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text"><font color='white'>Email: youremail@email.com</font></span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text"><font color='white'>Phone: + 1235 2355 98</font></span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </nav>
	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <p class="button-custom order-lg-last mb-0"><a href="appointment.html" class="btn btn-secondary py-2 px-3">Causeling</a></p>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">
	        	<li class="nav-item {{pajinauma}}"><a href="{% url 'vizitor:index' %}" class="nav-link pl-0">Uma</a></li>
	        	<li class="nav-item {{pajinakonaba}}"><a href="{% url 'vizitor:konaba' %}" class="nav-link">Konaba Sajobril</a></li>
	        	<li class="nav-item {{pajinaatividade}}"><a href="{% url 'vizitor:atividade' %}" class="nav-link">Atividade</a></li>
	        	<li class="nav-item {{pajinamisa}}"><a href="{% url 'vizitor:misa' %}" class="nav-link">Misa</a></li>
	        	<li class="nav-item {{pajinaeventu}}"><a href="{% url 'vizitor:eventu' %}" class="nav-link">Aventu</a></li>
	        	<li class="nav-item {{pajinaanunsiu}} "><a href="{% url 'vizitor:anunsiu' %}" class="nav-link">Anunsiu</a></li>
	          <li class="nav-item {{pajinaatendimentu}}"><a href="{% url 'vizitor:atendimentu' %}" class="nav-link">Atendimentu</a></li>
            <li class="nav-item {{pajinaplanu}}"><a href="{% url 'vizitor:planu' %}" class="nav-link">Planu Anual</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    
{% block content %}
{% endblock %}
		
    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-5">
              <h2 class="ftco-heading-2 logo">Develop & hosted  by<br> .<span>AICTLIQ</span></h2>
              <p>Website ne'e dezenvolve no host iha assosciasaun ICT munisipiu liquica </p>
            </div>
          
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2">Iha Pergunta ruma?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Bele kontaktu ba numeru </span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+670 784433344</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>

	            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-5 ml-md-4">
              <h2 class="ftco-heading-2">Links</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Uma</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Konaba Sajobril</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Atividades</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Misa</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Eventu</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Atendemetu</a></li>
              </ul>
            </div>
            <div class="ftco-footer-widget mb-5 ml-md-4">
              <h2 class="ftco-heading-2">Atendimentu Counselink</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Problema social</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Konsulta orasaun</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Konsulta moras</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Konsulta atendimentu</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Halo keixa</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-5">
              <h2 class="ftco-heading-2"> Download  pnau anual no dokumentu sira </h2>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Share ba ita bo'ot nia kolega , familia nee'ebe hela iha munisi[iu likisa</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> Dec 25, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-5 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_2.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> Dec 25, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md">
          	<div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2">Opening Hours</h2>
            	<h3 class="open-hours pl-4"><span class="ion-ios-time mr-3"></span>We are open 24/7</h3>
            </div>
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2">Subscribe Us!</h2>
              <form action="#" class="subscribe-form">
                <div class="form-group">
                  <input type="text" class="form-control mb-2 text-center" placeholder="Enter email address">
                  <input type="submit" value="Subscribe" class="form-control submit px-3">
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script>  SAJOBRIL & ICTLIQ - All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">AICTLIQ</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <!-- <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div> -->


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script> -->
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
    
  </body>
</html>
